### ISSUE TITLE
Missing Key.cs file

### ISSUE THREAD

**Issue by ncarandini** [italia/18app#26]
One single file named `Keys.cs` is missing from this repository for security reasons, so to compile you need to manually create the file, and save it at the root level of the `Italia.DiciottoApp` project, with this code (where the keys values are fakes):
``` CSharp
namespace Italia.DiciottoApp
{
    public static class Keys
    {
        // Fake keys
        public static readonly string X_IBM_ClientId = "FakeClientId";
        public static readonly string X_IBM_ClientSecret = "FakeClientSecret";
    }
}
```
Obviously API calls will fail but you can use the fake services to test locally your code changes.

**Comment by alranel** [comment]
I propose to still commit that file, with empty credentials, so that contributors can still easily compile the project without finding this issue.  The file can overridden in your build toolchain (a common pattern is to use environment variables/defines in the build toolchain so that you don't even need to override the file).

**Comment by ncarandini** [comment]
Yes you're right @alranel.
Done with commit 512f387acce2a2565dbdaddad9ebbf1769fc28c3
